# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CodingTask' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'youtube-ios-player-helper'

  # Pods for CodingTask

end
